import { Layout } from "antd";
import { Content, Header } from "antd/lib/layout/layout";
import { Navbar, ProductList } from "components";
import useProduct from "hooks/use-product";
import Head from "next/head";
import { useEffect } from "react";

function Home({ per_page, page, category_name }) {
    const { getProductCategory, getProduct } = useProduct();
    useEffect(() => {
        getProductCategory();
        getProduct({ per_page, page, category_name });
    }, []);

    return (
        <div>
            <Head>
                <title>Assesment Adi Maulana Triadi</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <Header className="fixed top-0 w-full z-10">
                    <Navbar />
                </Header>
                <Content className="h-full pt-[50px]">
                    <ProductList />
                </Content>
            </Layout>
        </div>
    );
}

export async function getServerSideProps(ctx) {
    const { per_page = 10, page = 1, category_name = "" } = ctx.query;

    return {
        props: {
            page,
            per_page,
            category_name,
        },
    };
}

export default Home;
