import { Layout } from "antd";
import { Content, Header } from "antd/lib/layout/layout";
import { Navbar, ProductList } from "components";
import useProduct from "hooks/use-product";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

function Home() {
    const { getProductCategory, getProduct } = useProduct();
    const router = useRouter();

    const { query } = router;

    useEffect(() => {
        getProductCategory();
        if (query) {
            const { per_page, page, category_name } = query;
            getProduct({ per_page, page, category_name });
        }
    }, []);

    return (
        <div>
            <Head>
                <title>Assesment Adi Maulana Triadi</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <Header className="fixed top-0 w-full z-10">
                    <Navbar />
                </Header>
                <Content className="h-full pt-[50px]">
                    <ProductList />
                </Content>
            </Layout>
        </div>
    );
}

export default Home;
